spring:
  cache:
    type: caffeine
    cache-names: average,cities
    caffeine:
      spec: expireAfterWrite=3600s

config:
  last-days: 3
  url: https://api.openweathermap.org/data/2.5/forecast
  appId:
  refresh-delay-cities: 600000 #10 min in milliseconds
logging:
  level:
    com.silaev.weather: DEBUG
